/*
Test generated by RoostGPT for test Bhhavya-Gherkin using AI Type Open AI and AI Model gpt-4

{
  background: null,
  rule: null,
  scenario: 'Delete an existing product\r\n' +
    '        Given there is an existing product with ID 1\r\n' +
    '        When the client sends a DELETE request to "/api/products/1"\r\n' +
    '        Then the response status code should be 200\r\n' +
    '        And the product with ID 1 should no longer exist',
  title: 'Delete an existing product'
}

*/
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class DeleteAnExistingProductTest {

    @BeforeEach
    public void setup() {
        RestAssured.baseURI = System.getenv("ROOST_SERVER_URL");
        RestAssured.basePath = "/api";
    }

    @Test
    public void deleteAnExistingProductTest() {
        // Given there is an existing product with ID 1
        int productId = 1;

        // When the client sends a DELETE request to "/api/products/1"
        Response response = given()
                .pathParam("productId", productId)
                .when()
                .delete("/products/{productId}");

        // Then the response status code should be 200
        response.then().statusCode(200);

        // And the product with ID 1 should no longer exist
        // This is implied by the 200 status code in the DELETE request.
        // To confirm, a GET request is made to the same endpoint, which should return a 404 status code.
        given()
                .pathParam("productId", productId)
                .when()
                .get("/products/{productId}")
                .then()
                .statusCode(404);
    }
}
