/*
Test generated by RoostGPT for test Bhhavya-Gherkin using AI Type Open AI and AI Model gpt-4

{
  background: null,
  rule: null,
  scenario: 'Get a product by ID\r\n' +
    '        Given there is an existing product with ID 1\r\n' +
    '        When the client sends a GET request "/api/products/1" to get a product by its id\r\n' +
    '        Then the response status code should be 200\r\n' +
    '        And the response should contain the product with ID 1',
  title: 'Get a product by ID'
}

*/
package com.bootexample4.RoostTest;

import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

public class getAProductByIdTest {

    @Test
    public void getProductById() {
        // Scenario: Get a product by ID
        // Given there is an existing product with ID 1
        // When the client sends a GET request "/api/products/1" to get a product by its id
        // Then the response status code should be 200
        // And the response should contain the product with ID 1

        String serverUrl = System.getenv("ROOST_SERVER_URL");
        String endpoint = "/api/products/1";

        given()
            .baseUri(serverUrl)
            .basePath(endpoint)
        .when()
            .get()
        .then()
            .assertThat()
            .statusCode(200)
            .body("id", equalTo(1));
    }
}
